LogEntry_0:
    exception: None
    currentDir: None
    importance: 5
    timestamp: '2019.09.03 19:34:57'
    msgType: 'status'
    message: 'Starting Manager configuration from c:\\users\\merlyn\\acq4\\config\\default.cfg'
    id: 1
LogEntry_1:
    exception: None
    currentDir: None
    importance: 5
    timestamp: '2019.09.03 19:34:58'
    msgType: 'status'
    message: '=== Device configuration complete ==='
    id: 2
LogEntry_2:
    exception: None
    currentDir: None
    importance: 5
    timestamp: '2019.09.03 19:34:58'
    msgType: 'status'
    message: '=== Setting base directory: C:\\users\\Merlyn\\desktop\\GEVI ==='
    id: 3
LogEntry_3:
    exception: None
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 8
    timestamp: '2019.09.03 19:34:58'
    msgType: 'warning'
    docs: ['userGuide/dataManagement.html#notes-and-logs']
    message: 'No log directory set. Log messages will not be stored.'
    id: 4
LogEntry_4:
    exception: None
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 5
    timestamp: '2019.09.03 19:34:58'
    msgType: 'status'
    message: 'Manager configuration complete.'
    id: 5
LogEntry_5:
    exception: None
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 9
    timestamp: '2019.09.03 19:34:58'
    msgType: 'status'
    message: u'ACQ4 version 0.9.3+gf3d17dab started.'
    id: 6
LogEntry_6:
    exception: None
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 8
    timestamp: '2019.09.03 19:37:02'
    msgType: 'warning'
    docs: ['userGuide/dataManagement.html#notes-and-logs']
    message: 'No log directory set. Log messages will not be stored.'
    id: 7
LogEntry_7:
    exception: None
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 8
    timestamp: '2019.09.03 19:37:24'
    msgType: 'warning'
    docs: ['userGuide/dataManagement.html#notes-and-logs']
    message: 'No log directory set. Log messages will not be stored.'
    id: 8
LogEntry_8:
    exception: None
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 8
    timestamp: '2019.09.03 19:38:07'
    msgType: 'warning'
    docs: ['userGuide/dataManagement.html#notes-and-logs']
    message: 'No log directory set. Log messages will not be stored.'
    id: 9
LogEntry_9:
    exception:
        message: 'IndexError: index 0 is out of bounds for axis 0 with size 0'
        traceback: ['Traceback (most recent call last):\n', '  File "multipatch_analysis\\ui\\acq4_modules.py", line 339, in load_from_dm_clicked\n    self.ui.load_data(sel_dir)\n', '  File "multipatch_analysis\\ui\\vimaging.py", line 84, in load_data\n    self._load_data(seqDir)\n', '  File "multipatch_analysis\\ui\\vimaging.py", line 175, in _load_data\n    self.roi_changed(None)\n', '  File "multipatch_analysis\\ui\\vimaging.py", line 222, in roi_changed\n    self.update_sequence_analysis()\n', '  File "multipatch_analysis\\ui\\vimaging.py", line 274, in update_sequence_analysis\n    base_starti, base_stopi, test_starti, test_stopi, noise_starti, noise_stopi = self.time_indices(img_t)\n', '  File "multipatch_analysis\\ui\\vimaging.py", line 248, in time_indices\n    base_stopi = np.argwhere(time_vals >= base_stop)[0,0]\n']
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 5
    timestamp: '2019.09.03 19:39:29'
    msgType: 'error'
    message: 'Unexpected error: '
    id: 10
LogEntry_10:
    exception:
        message: 'TypeError: tuple indices must be integers, not NoneType'
        traceback: ['Traceback (most recent call last):\n', '  File "c:\\users\\merlyn\\acq4\\acq4\\pyqtgraph\\imageview\\ImageView.py", line 495, in timeout\n    if self.currentIndex+n > self.image.shape[self.axes[\'t\']]:\n']
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 5
    timestamp: '2019.09.03 19:57:49'
    msgType: 'error'
    message: 'Unexpected error: '
    id: 11
LogEntry_11:
    exception:
        message: 'TypeError: tuple indices must be integers, not NoneType'
        traceback: ['Traceback (most recent call last):\n', '  File "c:\\users\\merlyn\\acq4\\acq4\\pyqtgraph\\imageview\\ImageView.py", line 495, in timeout\n    if self.currentIndex+n > self.image.shape[self.axes[\'t\']]:\n']
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 5
    timestamp: '2019.09.03 19:57:49'
    msgType: 'error'
    message: 'Unexpected error: '
    id: 12
LogEntry_12:
    exception:
        message: 'TypeError: tuple indices must be integers, not NoneType'
        traceback: ['Traceback (most recent call last):\n', '  File "c:\\users\\merlyn\\acq4\\acq4\\pyqtgraph\\imageview\\ImageView.py", line 495, in timeout\n    if self.currentIndex+n > self.image.shape[self.axes[\'t\']]:\n']
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 5
    timestamp: '2019.09.03 19:57:49'
    msgType: 'error'
    message: 'Unexpected error: '
    id: 13
LogEntry_13:
    exception:
        message: 'TypeError: tuple indices must be integers, not NoneType'
        traceback: ['Traceback (most recent call last):\n', '  File "c:\\users\\merlyn\\acq4\\acq4\\pyqtgraph\\imageview\\ImageView.py", line 495, in timeout\n    if self.currentIndex+n > self.image.shape[self.axes[\'t\']]:\n']
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 5
    timestamp: '2019.09.03 19:57:49'
    msgType: 'error'
    message: 'Unexpected error: '
    id: 14
LogEntry_14:
    exception:
        message: 'TypeError: tuple indices must be integers, not NoneType'
        traceback: ['Traceback (most recent call last):\n', '  File "c:\\users\\merlyn\\acq4\\acq4\\pyqtgraph\\imageview\\ImageView.py", line 495, in timeout\n    if self.currentIndex+n > self.image.shape[self.axes[\'t\']]:\n']
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 5
    timestamp: '2019.09.03 19:57:49'
    msgType: 'error'
    message: 'Unexpected error: '
    id: 15
LogEntry_15:
    exception:
        message: 'TypeError: tuple indices must be integers, not NoneType'
        traceback: ['Traceback (most recent call last):\n', '  File "c:\\users\\merlyn\\acq4\\acq4\\pyqtgraph\\imageview\\ImageView.py", line 495, in timeout\n    if self.currentIndex+n > self.image.shape[self.axes[\'t\']]:\n']
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 5
    timestamp: '2019.09.03 19:57:49'
    msgType: 'error'
    message: 'Unexpected error: '
    id: 16
LogEntry_16:
    exception:
        message: 'TypeError: tuple indices must be integers, not NoneType'
        traceback: ['Traceback (most recent call last):\n', '  File "c:\\users\\merlyn\\acq4\\acq4\\pyqtgraph\\imageview\\ImageView.py", line 495, in timeout\n    if self.currentIndex+n > self.image.shape[self.axes[\'t\']]:\n']
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 5
    timestamp: '2019.09.03 19:57:49'
    msgType: 'error'
    message: 'Unexpected error: '
    id: 17
LogEntry_17:
    exception:
        message: 'TypeError: tuple indices must be integers, not NoneType'
        traceback: ['Traceback (most recent call last):\n', '  File "c:\\users\\merlyn\\acq4\\acq4\\pyqtgraph\\imageview\\ImageView.py", line 495, in timeout\n    if self.currentIndex+n > self.image.shape[self.axes[\'t\']]:\n']
    currentDir: 'C:\\users\\Merlyn\\desktop\\GEVI'
    importance: 5
    timestamp: '2019.09.03 19:57:49'
    msgType: 'error'
    message: 'Unexpected error: '
    id: 18
